services:
  extractor_service:
    build:
      context: ./extractor_service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - "./input_directory:/app/input_directory"
      - "./output_directory:/app/output_directory"
    working_dir: /app
    entrypoint: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100" ]
